---
id: Mail
name: Mail
full: Mail library
description: >-
  A library that provides interfaces for sending e-mail messages and parsing
  e-mail addresses.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Mail
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/idna: ^2
      horde/mime: ^3
      horde/stream_filter: ^3
      horde/translation: ^3
      horde/util: ^3
  optional:
    composer:
      horde/smtp: ^2
      horde/stream_wrapper: ^3
      horde/test: ^3
      pear/net_dns2: ^1.5
      pear/net_smtp: ^1.9
